### ISSUE TITLE
[Feature request] - reflect code version in the "Select reference code"

### ISSUE THREAD

**Issue by Radiation-Transport** [JADE-V-V/JADE-WEB-APP#18]
**Is your feature request related to a problem? Please describe.**
The code version is not reflected in the window menu option.
![image](https://github.com/user-attachments/assets/2af60413-b621-41c0-b2a1-6fb6d3c3dea9)

**Describe the solution you'd like**
Insert the code version as it is present in the json CSV.

**Describe alternatives you've considered**
Leave as it is.

**Comment by dodu94** [comment]
there is no plan to support differences in the code version at the moment. It would complicate too much the structure. If you agree that we can live without that for the moment please close this issue
